<? $pageTitle = $this->layout()->pageTitle ='Change Your Password' ?>

<?php if ($this->hasFlash('success')): ?>

    <h3>Your password has been changed.</h3>

<?php else: ?>

    <?php $form->setAttribute('action', $this->basePath('/change_password')) ?>

    <h3><?= $pageTitle ?></h3>
    <p>Use the form below to change your password.</p>

    <?= $this->form()->openTag($form) ?>
    <p>
    <?= $this->formLabel($form->get('current_password')) ?><br/>
    <?= $this->formPassword($form->get('current_password')) ?>
    <?= $this->formElementError($form->get('current_password')) ?>
    </p>
    <p>
    <?= $this->formLabel($form->get('new_password')) ?><br/>
    <?= $this->formPassword($form->get('new_password')) ?> 
    <?= $this->formElementError($form->get('new_password')) ?> <small>Must be between 6 and 20 characters long, with at least one lowercase letter, one uppercase letter, and one number.</small>
    </p>
    <p>
    <?= $this->formLabel($form->get('confirm_password')) ?><br/>
    <?= $this->formPassword($form->get('confirm_password')) ?>
    <?= $this->formElementError($form->get('confirm_password')) ?>
    </p>
    <?= html_entity_decode($this->formRow($form->get('submit'))) ?>
    <?= $this->form()->closeTag($form) ?>

<?php endif ?>
