<?php $this->layout()->pageTitle = 'Forgot Your Password?'  ?>

<?php if ($this->hasFlash('success')): ?>

    <h3>Your password has been changed.</h3>
    <p>You will receive the new, temporary password via email. Once you have logged in with this new password, you may change it by clicking on the "Change Password" link.</p>

<?php else: ?>

    <?php $form->setAttribute('action', $this->basePath('/forgot_password')) ?>

    <h3>Reset Your Password</h3>
    <p>Enter your email address below to reset your password.</p>

    <?= $this->form()->openTag($form) ?>
    <p>
    <?= $this->formLabel($form->get('email')) ?><br/>
    <?= $this->formText($form->get('email')) ?>
    <?= $this->FormElementError($form->get('email')) ?>
    </p>
    <?= html_entity_decode($this->formRow($form->get('submit'))) ?>
    <?= $this->form()->closeTag($form) ?>

<?php endif ?>
