<?php $this->pageTitle = $this->layout()->pageTitle = 'About' ?>

<h3><?= $this->pageTitle ?></h3>

<br/>

<p><em>Knowledge is Power</em> is the first example from the book <a href="http://www.larryullman.com/books/effortless-e-commerce-with-php-and-mysql/">Effortless E-Commerce with PHP and MySQL</a></a> by Larry Ullman</p>
<p>Original code by Larry Ullman. Zend Framework 2 version by hush2.</p>

<h4>Credits</h4>

<p>Common Attack tips from <a href="http://www.cmswire.com/cms/web-cms/how-they-hack-your-website-overview-of-common-techniques-002339.php">CMSWire</a></p>
<p>Database Security tips from <a href="https://securosis.com/blog/database-security-fundamentals-access-authorization/">Securosis</a></p>
<p>General Web Security tips from <a href="http://web.appstorm.net/roundups/self-publishing/15-great-ways-to-secure-your-website/">Web.AppStorm</a></p>
<p>PHP Security tips from <a href="http://www.ultramegatech.com/2009/08/5-basic-php-security-tips/">UltraMega</a></p>